#!/bin/bash
java -jar -Dspring.config.location=config/ etung-iot-demo1.0.1-SNAPSHOT.jar --spring.profiles.active=dev --server.port=8978
~                                                                                                                                     
